### ISSUE TITLE
Master Quest Map tile O6 won't show the location of fairy cloth

### ISSUE THREAD

**Issue by MarceloLugo27** [Fabian-F/HyruleWarriorsHelper#3]
Adding images for reference (The cloth in question is located in Hilltop Keep)

![imagen](https://github.com/Fabian-F/HyruleWarriorsHelper/assets/17288447/ca041f65-cc16-4412-b7f2-1ba304dd7c27)

![imagen](https://github.com/Fabian-F/HyruleWarriorsHelper/assets/17288447/a99b2acf-d701-4937-986c-f9ff60a5525a)

**Comment by Fabian-F** [comment]
Hi, thank you!
Im gonna fix this with the next commit :)

**Comment by Fabian-F** [comment]
Added it and redeployed the app.
Please check if its correct now and close this issue if its resolved 😄

**Comment by MarceloLugo27** [comment]
Everything is fixed, thanks.

**Comment by MarceloLugo27** [comment]
Closing issue.
