### ISSUE TITLE
Master Quest map tile O3 is not showing fairy cloth treasure

### ISSUE THREAD

**Issue by MarceloLugo27** [Fabian-F/HyruleWarriorsHelper#4]
Adding image for reference: 

![imagen](https://github.com/Fabian-F/HyruleWarriorsHelper/assets/17288447/e331bd64-1a4e-42e5-903a-43637d13966b)

![imagen](https://github.com/Fabian-F/HyruleWarriorsHelper/assets/17288447/4e2995e4-c1e0-41d0-b844-547b2856ef60)

**Comment by Fabian-F** [comment]
Hi, thank you again!
It seems like I made a lot of mistakes while gathering the info for the master quest map, so I appreciate every finding!
Should be added and fixed now :)

**Comment by MarceloLugo27** [comment]
No problem. I will check for more errors as I play, this page has been really useful!
